version: 2
updates:
  # Dependabot will create PRs to update our third party github actions versions
  - package-ecosystem: github-actions
    open-pull-requests-limit: 100
    directory: /
    schedule:
      time: "16:00"
      interval: daily
    allow:
      - dependency-type: all

  - package-ecosystem: gomod
    open-pull-requests-limit: 100
    directory: /
    schedule:
      time: "16:00"
      interval: daily
    allow:
      - dependency-type: all
