linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - ireturn
    - maintidx
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - paralleltest
    - predeclared
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true
  goconst:
    min-occurrences: 3
  gocognit:
    min-complexity: 20
  gocyclo:
    min-complexity: 20
  mnd:
    ignored-numbers: ["0", "1"]
    ignored-functions: ["cobra.*", "strconv.*"]
  makezero:
    always: true
  nakedret:
    max-func-lines: 0
  nolintlint:
    require-specific: true
  whitespace:
    multi-if: true
    multi-func: true

issues:
  max-same-issues: 0 # unlimited
  max-issues-per-linter: 0 # unlimited

  exclude-rules:
    - path: cmd/
      linters:
        - wrapcheck
    - path: _test.go
      linters:
        - funlen
        - maintidx
        - gocognit
        - mnd
        - wrapcheck
