version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - ireturn
    - maintidx
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - paralleltest
    - predeclared
    - staticcheck
    - tagliatelle
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocognit:
      min-complexity: 20
    goconst:
      min-occurrences: 3
    gocyclo:
      min-complexity: 20
    makezero:
      always: true
    mnd:
      ignored-numbers:
        - "0"
        - "1"
      ignored-functions:
        - cobra.*
        - strconv.*
    nakedret:
      max-func-lines: 0
    nolintlint:
      require-specific: true
    whitespace:
      multi-if: true
      multi-func: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - wrapcheck
        path: cmd/
      - linters:
          - funlen
          - gocognit
          - maintidx
          - mnd
          - wrapcheck
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
