project_name: lock-exec
before:
  hooks:
    - go mod download
builds:
  - id: lock-exec
    binary: lock-exec
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - arm
      - arm64
      - amd64
    env:
      - CGO_ENABLED=0
archives:
  - id: lock-exec
    format: binary
release:
  prerelease: auto
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
dockers:
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/loomhq/lock-exec:latest
      - ghcr.io/loomhq/lock-exec:{{ .Version }}
      - ghcr.io/loomhq/lock-exec:{{ .Major }}
      - ghcr.io/loomhq/lock-exec:{{ .Major }}.{{ .Minor }}
