version: 2.1

orbs:
  go: circleci/go@1.3.0
  loom-go: loomhq/go@6.2.0
  loom-docker: loomhq/docker@1.5.0
  docker: circleci/docker@1.0.1

jobs:
  test:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run:
          name: test
          command: |
            set -ex
            git config --global url."https://x-oauth-basic:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
            go test -v ./...

  build-and-test:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - run:
          name: gitconfig
          command: |
            set -ex
            git config --global url."https://x-oauth-basic:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true

      - attach_workspace:
          at: /home/circleci/

      - run:
          name: build mac binaries
          command: |
            mkdir /home/circleci/build

            GOOS=darwin GOARCH=amd64 go build -o /home/circleci/build ./...

      - run:
          name: build linux binaries
          command: |
            GOOS=linux GOARCH=amd64 go build -o /home/circleci/build ./...

      - persist_to_workspace:
          root: ~/
          paths: build/

      - store_artifacts:
          path: /home/circleci/build

workflows:
  version: 2
  build:
    jobs:
      - loom-go/lint:
          context: infra
      - build-and-test:
          requires:
            - loom-go/lint
          context: infra

  build-deploy:
    jobs:
      - loom-go/lint:
          context: infra
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[vV]\d+\.\d+\.\d+/

