name: Validate

on:
  workflow_dispatch:
  push:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable # https://golang.org/dl/
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
      - name: Goreleaser Check
        uses: goreleaser/goreleaser-action@v6.2.1
        with:
          args: check
      - name: Go Mod Tidy
        run: test -z $(go mod tidy)
      - name: Lint
        uses: golangci/golangci-lint-action@v6.4.1
      - name: Test
        run: go test -race -cover -v ./...
      - name: Run govulncheck
        run: govulncheck ./...
